### ISSUE TITLE
Conflicting options: --rm and -d

### ISSUE THREAD

**Issue by prashant7july** [shiphp/weather-app#1]
Hi,

In case of Run the MySQL Database: docker run -d --rm --name weather-db -e MYSQL_USER=admin -e MYSQL_DATABASE=weather -e MYSQL_PASSWORD=p23l%v11p -e MYSQL_RANDOM_ROOT_PASSWORD=true -v $(pwd)/.data:/var/lib/mysql mysql:5.7

Getting Conflicting options: --rm and -d

**Comment by karllhughes** [comment]
Hey @prashant7july I have not seen this issue. What version of Docker are you running (just run `docker -v` in the command line to see)? Be sure to upgrade to the latest version.

**Comment by karllhughes** [comment]
You could also just leave `--rm` out of your command if you can't get it to work. You'll just want to manually remove the container when you're done with the database.

**Comment by prashant7july** [comment]
Hi, Can you just suggest, how to upgrade the docker version? Please

**Comment by karllhughes** [comment]
It depends on your host operating system. You may have to uninstall and reinstall. Here's the link to Docker's documentation for upgrading: https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/
